### ISSUE TITLE
config for old f1al 2015 mod

### ISSUE THREAD

**Issue by EdgeGMR** [ac-custom-shaders-patch/acc-extension-config#100]
[f1al.zip](https://github.com/ac-custom-shaders-patch/acc-extension-config/files/6105799/f1al.zip)
config for these car after got them work with AC latest pls add  it

**Comment by EdgeGMR** [comment]
[f1al_2015.zip](https://github.com/ac-custom-shaders-patch/acc-extension-config/files/6105811/f1al_2015.zip)
texture

**Comment by RustyChest** [comment]
Learn how to make a pull request.
