### ISSUE TITLE
OpenVr mirroring to monitor is stretched and has extreme FOV compared to the normal output of oculus in rendering

### ISSUE THREAD

**Issue by ChickenLoverD** [ac-custom-shaders-patch/acc-extension-config#130]
When selected the oculus rendering mode with oculus headset the mirror on the monitor the fov and resolution fits the monitor properly and looks nice while when you use OpenVr the output is competlly stretched and the FOV is weird.

**Comment by gro-ove** [comment]
That isn’t really a CSP bug, AC always was like that. That’s why I added custom VR mirroring in VR tweaks. Next CSP update is going to have a uniform-stretch-to-fill option there as well, so it would match the way Oculus mirroring looks.
