### ISSUE TITLE
Issue with managing car setups in AC with CSP 0.1.74 and 0.1.75

### ISSUE THREAD

**Issue by kpok** [ac-custom-shaders-patch/acc-extension-config#135]
Hello, I would like to raise a bug which occurs in version of CSP 0.1.74 and 0.1.75. I checked also version 0.1.73 and the bug does not occur on version 0.1.73:

It is related to saving new setups in AC:

I used configuration (Porsche 911 GT3 Cup 2017 / Magione) but this issue occur on many configurations.
Before each scenario I emptied directory with setups for above configuration.

Scenario 1:
1. Open new session (Porsche 911 GT3 Cup 2017 / Magione)
2. Go to setup and save setup as ini1.
3. Reset to default and create new different setup ini2.
4. Load setup ini1  - notice that ini1 setup has exactly the same configuration as ini2 (previous config of ini1 is gone.)

Scenario 2:
1. Open new session (Porsche 911 GT3 Cup 2017 / Magione)
2. Go to setup and save setup as ini1.
3. Make some configuration changes and try to save changes to ini1 - notice in previous versions and without CSP - the GUI asks if I want to ovewrite changes. In versions 74 and 75 the changes are applied immediately.

Scenario 3:
1. Open new session (Porsche 911 GT3 Cup 2017 / Magione)
2. Go to setup and save setup as ini1.
3. Exit session.
4. Open new session (Porsche 911 GT3 Cup 2017 / Magione)
5. Create new different setup and save it as ini2.
6. Load setup ini1.
7. Load setup ini2 - notice that ini2 configuration is the same as ini1 saved in point 2. Configuration of ini2 from point 5 is gone.

Scenario 4:
1. Open new session (Porsche 911 GT3 Cup 2017 / Magione)
2. Go to setup and save setup as ini1.
3. Delete setup ini1 - notice that GUI asks if i am sure to delete setup. After confirm setup stays in Setup window.

**Comment by Marocco2** [comment]
Should be fixed in 0.1.76

**Comment by DeRoc2** [comment]
Hello - 
I notice now that v1.76 will write a new setup file, but will not modify it after the first save.
The file-date changes but nothing new is written to the file.
Confirmed with numerous file saves, overwrite, re-load setups, but only the first saved version is ever re-loaded.
Thank you!
