### ISSUE TITLE
Replaced mirror of Ferrari 488 GT3  is reversed

### ISSUE THREAD

**Issue by toepi** [ac-custom-shaders-patch/acc-extension-config#137]
after the merge of #133 the mirror works in 0.1.75, but in 0.1.76 it is still swapped (left side is shown on the right). This makes the defense very difficult.

Tried to solve it myself. But was not able to get the mirror mesh. In the latest object inspector it does not work in older one the mirror is not selectable only the dashboard or the track.

So please can someone who knows how it works fix it.

Btw the buttons don't work either :(.

**Comment by toepi** [comment]
@Blumlaut: yes the pr doesn't cause it. it was there before (with lights-patch-v0.1.76-preview92-full).

**Comment by Marocco2** [comment]
Still present in 0.1.76?

**Comment by Marocco2** [comment]
Close due stall
