### ISSUE TITLE
PBR breaks skinned meshes

### ISSUE THREAD

**Issue by goddamn-is-this-available** [ac-custom-shaders-patch/acc-extension-config#140]
When PBR is applied to a skinned mesh part the shader is applied, but the animation breaks: mesh stays static during animation. For example, use leather PBR on any skinned shifter boot in any car that has one and observe the shifter while changing gears.

**Comment by goddamn-is-this-available** [comment]
Any updates? Kinda sucks to have a fully PBR'ed car minus shifter boot.

**Comment by goddamn-is-this-available** [comment]
Still no PBR on skinned meshes in the current public CSP build.

**Comment by gro-ove** [comment]
I’ll work on that, thanks

**Comment by Marocco2** [comment]
Still present in 0.1.77 public?
