### ISSUE TITLE
Enable smoke in custom showroom

### ISSUE THREAD

**Issue by ImagineerNL** [ac-custom-shaders-patch/acc-extension-config#150]
Current showroom is unable to handle smoke/fog/whatever like you can create in Blender. CSP is able to handle smoke in ext_config like

```
[SMOKE_1]
    POSITION = 0, 0, 0
    DIRECTION = 0, 2, -2
    SPEED = 25
    SIZE = 1
    COLOR = 1, 0.3, 0.0, 1
    SPREAD = 7
    INTENSITY = 1
```
Could this be incorporated in the showroom as well?
    
Example of smoke in-game (just a testvid) https://www.youtube.com/watch?v=LvAkAU4x370

**Comment by Trava715** [comment]
No. CM showroom is incompatible with CSP and there's no indication it will ever be.
