### ISSUE TITLE
Issue with real mirrors

### ISSUE THREAD

**Issue by Cotocolmenas** [ac-custom-shaders-patch/acc-extension-config#154]
Hi!. I have an issue with the real mirrors. The most of the cars don't have this problem but others like f2004 or r25 have this problem, where the half of the mirror is "under" the bodywork, as you can see. I believe the problem is because in this cars, the mirrors are very close to the car, so the clip planes are too short for rendering all the car. I would like to know how to decrease the minimum value of the clip planes in order to see the mirror properly. Thanks in advance!
![cap](https://user-images.githubusercontent.com/95507293/144681321-27a19ce6-5ecc-4641-89ca-d49d505258ce.png)
![Captura](https://user-images.githubusercontent.com/95507293/144681336-6e4b8675-6672-4aa4-91e5-bed94c8987ac.JPG)

**Comment by leBluem** [comment]
With "Smart Mirrors" enabled go into cockpit view and use mirror app to change the mirrors, then it should be correct then in the view you posted
mirror app: https://github.com/ac-custom-shaders-patch/acc-extension-apps
