### ISSUE TITLE
CULL_MODE = DOUBLESIDED added faces do not reflect light

### ISSUE THREAD

**Issue by PlasticTangerine** [ac-custom-shaders-patch/acc-extension-config#165]
When using `CULL_MODE = DOUBLESIDED` the added faces do not reflect light.

My config:
```INI
[SHADER_REPLACEMENT_...]
ACTIVE=1
MATERIALS = Material3
CULL_MODE = DOUBLESIDED
```
In game:

![image](https://user-images.githubusercontent.com/74761423/149041696-0980b051-9311-4f60-b729-9fdb05f820c2.png)

Tested on 0.1.76

**Comment by Trava715** [comment]
You really shouldn't use this for any purpose other than debug if that's what you're planning on.

**Comment by gro-ove** [comment]
Thanks for the report, but this is intended behaviour. Faces don’t get culled, but they still reflect light based on their normals, and those normals do not get inverted for back sides. I might add normals inversion later, but I worry this change, while fixing a few specific cases, might add a bit of overhead for everything else as well.

Instead, you can use mesh split with faces inversion:

```ini
[MESH_SPLIT_...]
MESHES = mesh_name
MODE = COPY_FLIPPED
```

Although it would add extra mesh and thus another draw call. What shader do you use? I think I could safely add normal inversion to some simpler shader, like ksPerPixelAT (for which it seems like it might be generally useful in some cases to save on triangles).

**Comment by PlasticTangerine** [comment]
I was using this mode for quick debugging and noticed light wasn't reflecting and thought it could be a potential issue.  If this is the intended behavior, I am fine with this issue being closed as is.  No need for additional shading modes, etc.
