### ISSUE TITLE
Motion blur picking up parts of the car close to the ground (again)

### ISSUE THREAD

**Issue by Trava715** [ac-custom-shaders-patch/acc-extension-config#168]
![image](https://user-images.githubusercontent.com/43389722/149294352-de63232b-84b2-40ff-a82a-88e124911c32.png)

Has been fixed before and came back after motion blur shader rewrite.
![image](https://user-images.githubusercontent.com/43389722/149294747-e7a34140-dc3f-44a8-89bb-e5a89d48d534.png)

**Comment by goddamn-is-this-available** [comment]
Been like that since several recent public CSP releases.

**Comment by Marocco2** [comment]
Still present in 0.1.78?

**Comment by Blumlaut** [comment]
could not reproduce this on `0.1.79-preview5`
![image](https://user-images.githubusercontent.com/13604413/172721954-e95596f7-b1b1-4a11-bb04-807d358a1bdd.png)
