### ISSUE TITLE
RSS Lanzo GTM RaceLogic and Time Delta broken

### ISSUE THREAD

**Issue by chas1723** [ac-custom-shaders-patch/acc-extension-config#176]
the RSS Lanzo GTM no longer has a functioning racelogic or time delta on the main dash display.  The racelogic should have a bar that goes across the bottom of it that represents the time delta and it should be green for negative and red for positive.  The Main dash also has a time delta that should be color coded red to the left for negative and blue to the right for positive.  It does nothing in the negative and goes both directions when in the positive.  I am unsure when this broke.  The Bayro in the set of cars has functioning racelogic.

https://www.youtube.com/watch?v=4u75uwk7EaI&t=199s

**Comment by gro-ove** [comment]
Sadly that’s a problem with config. I should make a post describing how to set up those bars. They missed a few points: red bar should have been inverted, and white bar should have had culling set to doublesided.

**Comment by chas1723** [comment]
I will advise RSS and hopefully get this worked out.  It is quite strange that the Bayro in the set has functioning RaceLogic but the Lanzo does not.  It must be the added time delta on the main dash that has affected the RaceLogic and broken both functions.

**Comment by chas1723** [comment]
could you explain a bit more about the Gain/Loss red and blue bars on the main display?  I see where they made the mistake on the RaceLogic and have fixed that.

**Comment by chas1723** [comment]
These are the two areas in the config for this gauge.  Blue is for gaining time and it is CSP_C.  Red is loosing time and is CSP_D.  the fact they mirror each other tells me the config is wrong as they will come on at the same time.  

[ANALOG_INDICATOR_...]
INPUT = PERF_METER
INPUT_MULT = 4
NAME = CSP_C
SCALE_START = -1, 1, 1
SCALE_END = 1
SPEED_LAG = 0
LOWER_BOUND = 0
UPPER_BOUND = 1

[ANALOG_INDICATOR_...]
INPUT = PERF_METER
INPUT_MULT = 4
NAME = CSP_D
SCALE_START = -1, 1, 1
SCALE_END = 1
SPEED_LAG = 0
LOWER_BOUND = 0
UPPER_BOUND = 1

**Comment by gro-ove** [comment]
Sure, here is a working version:

```ini
[SHADER_REPLACEMENT_...]
MESHES = CSP_B
CULL_MODE = DOUBLESIDED  ; needed for bar to be visible when it has negative scale

; single white bar:
[ANALOG_INDICATOR_...]
INPUT = PERF_METER
INPUT_MULT = 4
NAME = CSP_B
SPEED_LAG = 0
LOWER_BOUND = -1        ; goes from -1
UPPER_BOUND = 1         ; to 1
RANGE = 0               ; a small fix for negative values to work reliably
SCALE_START = -1, 1, 1  ; scale when value is at its starting point (-1)
SCALE_END = 1           ; scale for ending point (1, 1, 1)

; blue part of two-colored bar:
[ANALOG_INDICATOR_...]
INPUT = PERF_METER
INPUT_MULT = 4
NAME = CSP_C
LOWER_BOUND = 0
UPPER_BOUND = 1
SCALE_START = 0, 1, 1 ; starting with 0 scale at 0 point (set in LOWER_BOUND)
SCALE_END = 1
SPEED_LAG = 0

; red part of two-colored bar:
[ANALOG_INDICATOR_...]
INPUT = PERF_METER
INPUT_MULT = -4  ; negative multiplier
NAME = CSP_D
LOWER_BOUND = 0
UPPER_BOUND = 1
SCALE_START = 0, 1, 1 ; starting with 0 scale at 0 point (set in LOWER_BOUND)
SCALE_END = 1
SPEED_LAG = 0
```

By the way, you can test it easily by replacing PERF_METER by STEER and scaling down INPUT_MULT to something like 0.04.

**Comment by chas1723** [comment]
thank you.  This version seems to get things working better but the racelogic white bar is black in this version.

**Comment by chas1723** [comment]
[SHADER_REPLACEMENT_...]
MESHES = CSP_B
CULL_MODE = DOUBLESIDED

; single white bar:
[ANALOG_INDICATOR_...]
INPUT = PERF_METER
INPUT_MULT = 0.25
NAME = CSP_B
SPEED_LAG = 0
LOWER_BOUND = -1        ; goes from -1
UPPER_BOUND = 1         ; to 1
RANGE = 0               ; a small fix for negative values to work reliably
SCALE_START = -1, 1, 1  ; scale when value is at its starting point (-1)
SCALE_END = 1           ; scale for ending point (1, 1, 1)

; red part of two-colored bar:
[ANALOG_INDICATOR_...]
INPUT = PERF_METER
INPUT_MULT = 1
NAME = CSP_D
LOWER_BOUND = 0
UPPER_BOUND = 1
SCALE_START = 0, 1, 1 ; starting with 0 scale at 0 point (set in LOWER_BOUND)
SCALE_END = 1
SPEED_LAG = 0

; blue part of two-colored bar:
[ANALOG_INDICATOR_...]
INPUT = PERF_METER
INPUT_MULT = -1  ; negative multiplier
NAME = CSP_C
LOWER_BOUND = 0
UPPER_BOUND = 1
SCALE_START = 0, 1, 1 ; starting with 0 scale at 0 point (set in LOWER_BOUND)
SCALE_END = 1
SPEED_LAG = 0

**Comment by chas1723** [comment]
this fixed it completely for me.  the INPUT_MULT was off in your example and the colors were reversed but you got me on the right track so Thank You for that.  This can be marked as fixed as I have done some testing and it works perfectly now.

**Comment by gro-ove** [comment]
Great, thank you!
