### ISSUE TITLE
LOD issues with certain cars

### ISSUE THREAD

**Issue by chas1723** [ac-custom-shaders-patch/acc-extension-config#177]
Since preview 1.76 came out, several cars have been having what appears to be LOD issues.  Many cars that have replaceable parts in the car setup will have those parts disappear at distance if selected.  One is the RSS GT Vortex V10.  It has multiple light configurations on the front.  If you select the enduro lights, fog lights, or main light covers they will disappear at a distance.  This happens to other cars as well such as the VRC_pt_auriel8, vrc_arc_auriel90, and several other cars.

https://www.youtube.com/watch?v=yPR--J5bIB8

**Comment by gro-ove** [comment]
Thank you for the report, will fix.

**Comment by chas1723** [comment]
Thank you

**Comment by chas1723** [comment]
the issues appears to be solved minus the issue with the Vortex #206
