### ISSUE TITLE
1.77p1 broke track extensions

### ISSUE THREAD

**Issue by chas1723** [ac-custom-shaders-patch/acc-extension-config#178]
It seems that 1.77p1 has broken the ability to consistently use track extensions that make use of a zip file to hold textures.  Many times the tracks will crash on loading.  If they do load, you are greeted with black textures everywhere.  It does not happen 100% of the time but it does happen most of the time.  Many of Pyyer's extensions on racedepartment suffer from this as well as Johnr777's retexture of spa.  He released an update and took all the textures out of the zip and it load fine now.  if you download his original (ver. 0.9) release you will see the issue.
https://www.racedepartment.com/downloads/spa-remastered.43055/

**Comment by gro-ove** [comment]
Fix is coming soon, thank you. Very sorry for the inconvenience.

**Comment by chas1723** [comment]
thank you for looking into the issue.  I am sure the track skin/extension makers will be pleased to hear it is fixed.

**Comment by Blumlaut** [comment]
afaik this has been fixed with 77, can anyone confirm?
