### ISSUE TITLE
[VANILLA ISSUE] ABS setup page not working correctly

### ISSUE THREAD

**Issue by Trava715** [ac-custom-shaders-patch/acc-extension-config#188]
If ABS is set to 
```
PRESENT=1
ACTIVE=0
```
in electronics.ini, ABS cannot be adjusted from the setup menu
![image](https://user-images.githubusercontent.com/43389722/151312660-6912d469-3d80-42bc-aff8-9a0da700ca5b.png)

 but can be adjusted from inside the car. Possible fix via CSP, at least for extended-2 cars?

**Comment by gro-ove** [comment]
Will be fixed for all cars (I think it should be ok considering it can be changed with a keyboard shortcut), thanks for the report

**Comment by Trava715** [comment]
Fixed in 1.77 Preview 85
