### ISSUE TITLE
The tracks do not work: Brands Hatch, Highlands, Macau Guia Circuit, Mugello.

### ISSUE THREAD

**Issue by Deskit** [ac-custom-shaders-patch/acc-extension-config#19]
All tracks by the author "NoThrottleControl aka nptc364" do not work, with "Custom shaders patch" Activate.

Tracks configs:

Brands Hatch: 453
Highlands: 452
Macau Guia Circuit: 452
Mugello: 454

My Shaders Patch Version is 0.1.25-preview49 recommended

**Comment by chrisraff** [comment]
Mugello was crashing the launcher for me, and I found that replacing the version of mugello.ini that Content Manager downloaded with the version on github allowed me to load into Mugello with no problems.

**Comment by RustyChest** [comment]
patch version 49 is no longer the recommended version, it is currently patch version (preview) 140. Check that you have installed the patch and (presumably) Sol properly by using this form https://forms.gle/tMzfAh3Sej5jz6pLA
