### ISSUE TITLE
Real Mirrors - Incorrect FoV vs distance calculation

### ISSUE THREAD

**Issue by Trava715** [ac-custom-shaders-patch/acc-extension-config#190]
Moving the camera closer to the mirror results in it's FoV decreasing instead of increasing.
![image](https://user-images.githubusercontent.com/43389722/151710560-d292ce16-3c7b-48c6-86d8-8102266bf380.png)
![image](https://user-images.githubusercontent.com/43389722/151710563-5a3f5ecb-549c-44c0-81b6-54714679cfb2.png)

Tested on CSP 1.74 public.

**Comment by gro-ove** [comment]
Option for Real Mirror mirrors to change FOV with distance was added in 0.1.76, before that FOV was fixed.

**Comment by Trava715** [comment]
1.76 with "Alter FOV" enabled produces correct behavior.
