### ISSUE TITLE
Walking Out crashing the game in trackday mode

### ISSUE THREAD

**Issue by Tougeinsk** [ac-custom-shaders-patch/acc-extension-config#191]
On previews and versions higher than 1.76 p63, walking out mode when enabled simply crashes on the Audio part of loading. It is impossible to get into game in trackday mode with this on and cannot be used at all, suspected to be something to do with the new features added to walking out after this preview.

Tested on 1.76 and above

**Comment by Trava715** [comment]
Cannot reproduce on my end.
![image](https://user-images.githubusercontent.com/43389722/153297085-aab1ae14-f5ea-4b33-a631-95c1e8fae6bc.png)
![image](https://user-images.githubusercontent.com/43389722/153297096-056456e8-ccfa-48e4-8528-11f0f5a1b99e.png)
![image](https://user-images.githubusercontent.com/43389722/153297103-c514ebee-6661-4cba-9b36-45f4c2094d80.png)

**Comment by Trava715** [comment]
For posterity: Issue caused by the rev beeper app bundled with DDM RX7
