### ISSUE TITLE
dry track acts as if it is wet

### ISSUE THREAD

**Issue by chas1723** [ac-custom-shaders-patch/acc-extension-config#196]
So for the past few previews I have notice some tracks will show water coming off the tires when the track is dry.   You will even see water spray behind the vehicle.  This video was taken at Road Atlanta by Johnr777 with the RSS Lanzo GTM car.  I am running 1.77p1 with Pure 0.74

https://youtu.be/YGVZ1nfXcpY

**Comment by Marocco2** [comment]
Is RSS Lanzo GTM car have extended physics enabled via CM?

**Comment by chas1723** [comment]
I have extended physics enabled in content manager.  More than just this car does it.  I will provide examples of other cars once I can get back home to check.

**Comment by Marocco2** [comment]
Ok, can confirm this happens switching from Rain to Dry weather

**Comment by Marocco2** [comment]
Doesn't appear in 0.1.78 on my end. Need a double check

**Comment by chas1723** [comment]
I have not been able to recreate this issue since updating to 1.78p1
