### ISSUE TITLE
some bugs, ai related

### ISSUE THREAD

**Issue by leBluem** [ac-custom-shaders-patch/acc-extension-config#211]
all present since a long time 

1st: in hotlap mode, with CTRL+C AI driving turned on, after the car has gone to pits it will not leave them again, restarting session always puts the AI driven car back in the pits...

2nd: 
-in a race, single player, when race is over (and maybe before ai opponents have finished the cooldown lap, which is enabled), 
-then restarting the session, (some) ai cars still want to go to the pits instead of going for the new race, maybe they forgot to re-fuel or something? ... just checked, switched view to them, yes, they have zero fuel left ; ( also with CTRL+C AI driving turned on )
![grafik](https://user-images.githubusercontent.com/24473940/155185976-ddf11176-d46d-48a8-a0e5-279cd599b90c.png)

3rd: mouse cursor disappearing randomly, again mostly with CTRL+C AI driving on, after using taskbar, but not only then...you cant click in any python app then, on the imgui apps the mouse cursor works though, but its still wonky on them too

4th: atm cant reproduce, its pretty random it seems : 
 -on start screen, before using the "wheel button" to start the session
 -when using shortcut CTRL+C to activate AI driving for player car - CSP crashes; in vanilla ctrl+c is just ignored; but as said its not reproducable anymore atm lol

(you might ignore the pattern of me using AI to drive the game, its just convenient mostly for testing :) )

**Comment by leBluem** [comment]
...and the default throttle limit for the out-lap might be a bit too low, on tracks with some hills, the AI will not make it over some of the steeper hills
![grafik](https://user-images.githubusercontent.com/24473940/155193257-7ba5372e-a9cc-492e-8ded-e2928ab86138.png)

**Comment by Marocco2** [comment]
@leBluem please try not bulk bugs by topics. Create issues per bug
