### ISSUE TITLE
Godrays broken on 0.1.77 release and 0.1.78 preview 1

### ISSUE THREAD

**Issue by ciba1991** [ac-custom-shaders-patch/acc-extension-config#223]
Godrays do not render with the latest two versions. Worked on 77p62, the changes in features lead me to believe the new filters from graphics adjustments could be related to the issue.

**Comment by Trava715** [comment]
Can't verify because godrays never worked for me. @Marocco2 ?

**Comment by Marocco2** [comment]
Godrays worked before 77 public. I didn't test 77 public or 78 Patreon. Gonna do it on weekend.

I need more info: weatherfx used, ppfilters etc.

**Comment by ciba1991** [comment]
weatherfx: Sol 2.2.1 and Pure 0.76, controller Sol 2.2
filters: Pure, PureEye, C13CameraObscura, default, fanatiC 1.4
possibly related settings: glare quality max in ac settings, sunrays enabled, dynamic shadows on or off, new filters not enabled, mirage like reflections enabled

**Comment by ciba1991** [comment]
peter boese found the probable issue: godrays colour not being set by default in sol or pure. so not a CSP issue per se. IMO this should be considered a non-issue and marked closed/solved
