### ISSUE TITLE
[CSP WIPERS] Car Instruments turned off causes CSP Wipers to be stuck at max position

### ISSUE THREAD

**Issue by Blumlaut** [ac-custom-shaders-patch/acc-extension-config#226]
When the CSP "Car Instruments" or "Lighting FX" option is entirely turned off, cars with wipers using csp will have them stuck at the maximum position defined in the ext_config

This was spotted while investigating #155, may not be related though, filing it here as a separate issue as i can't tell if they are related.

![image](https://user-images.githubusercontent.com/13604413/156900885-f20bbc1c-ddbb-4ec1-b61f-34fb9554c6c1.png)

**Comment by Trava715** [comment]
Either stuck at 180* or disappears completely.
![image](https://user-images.githubusercontent.com/43389722/156901927-fbf33a28-777c-4515-b9be-243e0e4afc1c.png)
![image](https://user-images.githubusercontent.com/43389722/156901930-8612aaa4-3d51-4f58-bc2b-b354273b494c.png)

**Comment by Blumlaut** [comment]
lighting fx off also causes this to happen.
