### ISSUE TITLE
[Feature request] Change car from available cars

### ISSUE THREAD

**Issue by petie** [ac-custom-shaders-patch/acc-extension-config#251]
Just like it's possible to change skins - make it possible to change the car to any other car loaded on the server.
Would that even be possible?

**Comment by Trava715** [comment]
That's a request for the ACServer team.
https://github.com/compujuckel/AssettoServer

**Comment by petie** [comment]
Is the skin change also implemented by the ACServer team?

**Comment by RustyChest** [comment]
CSP can dynamically hotload certain textures, allowing for the already existing framework of changing your car's color and more recently drawing liveries straight onto it. Something could probably be rigged up locally to swap those textures around but for it to be sync'd properly across all clients is a task for the acServer team. 

At the moment, building a skin-manager in-game is just not part of the scope of this project but we've provided a few tools to do so already.
