### ISSUE TITLE
[ANDROID AUTO]: Automatic screenshot trigger bound to gas/brake input (CSP 0.1.77+)

### ISSUE THREAD

**Issue by of17** [ac-custom-shaders-patch/acc-extension-config#262]
Judging from the [latest patreon post](https://www.patreon.com/posts/fixes-and-few-63136994) for the 0.1.77/0.1.78preview1 release this obviously started as some sort of tech demo/showcase but is now becoming increasingly annoying when actually driving the cars instead of playing around with Spotify and Youtube. I don't see the point of taking (non persistent) screenshots of the navigator/MMI when exceeding a certain throttle/brake threshold.

**Code in question:**
extension\lua\cars\android_auto\system.lua, Lines 1085 ff.:
```
if car.gas > 0.8 and car.brake > 0.8 and screenshotTime <= 0 then
    system.lastScreenshot = ui.ExtraCanvas(ui.windowSize())
    system.lastScreenshot:update(...)
```

The temporary solution is to comment/remove the block completely but this will obviously not survive the next update and not every user will be comfortable with messing with the CSP code on their fragile AC installations. Considering that people are already complaining about this on FB/Discord and with the increasing popularity of AA it would be nice if the trigger could be removed or engaged via key binding instead.

**Comment by Blumlaut** [comment]
i believe this was removed in 0.1.79, can be closed?
