### ISSUE TITLE
No dirt particles on cars anymore

### ISSUE THREAD

**Issue by ZaentYT** [ac-custom-shaders-patch/acc-extension-config#266]
For some reason, for the past 2 days, dirt gone missing from any kunos car, as well as some other mods (for example the bk audi r8 lms evo) that supported it, even on kunos tracks with gravel,  or reboot tracks that support it. Verifying steam integrity, updating, reinstalling diffrent versions of csp does not seem to help at all, nor did wiping my AC completely as well as cm, for a fresh install. And yes, I am using a csp preset (https://acstuff.ru/s/9PA4Dx -if any1 wants to try and help with troubleshooting) that should be good enough, resetting it or the video settings does not change anything.  (Video settings are here: https://acstuff.ru/s/QmDb5p )

Example of no dirt:
![image](https://user-images.githubusercontent.com/3944248/166141198-2d3898ff-fce6-434d-9780-3509bd9b126f.png)
How it should be (examples with the bk r8 having dirt particles on it generating by running of track/in the gravel)
![image](https://user-images.githubusercontent.com/3944248/166141208-a955fcd8-3779-4e5e-8181-6c3a9000cd7d.png)
![image](https://user-images.githubusercontent.com/3944248/166141213-d577225f-203c-4887-b737-d5e2acbdd9cb.png)

**Comment by CheesyManiac** [comment]
@Marocco2 
This appears to be fixed with CSP 1.79 and onwards
![image](https://user-images.githubusercontent.com/93444114/216771082-9a27ce63-0f0b-4db3-af50-f14326b7c0e7.png)
