### ISSUE TITLE
[VR] -Single Pass Stereo - refraction lights blurred for right eye in VR

### ISSUE THREAD

**Issue by YacobDoodjack** [ac-custom-shaders-patch/acc-extension-config#283]
When I turn on Single Pass Stereo, the refraction lights on cars looks blurred and "moving" in right eye. Image in left eye is normal. DDM mod cars and Kunos cars with refraction configs (like Benz 190E EVO II DTM) are examples of this problem: 

https://youtu.be/D0jzIFiNd9U

Bluriness can be fixed by disabling refraction TAA (CSP Graphic Adjustments -> Accesible color buffer -> disable "Full resolution for better quality"):

![obraz](https://user-images.githubusercontent.com/107269401/173333702-0c3932df-4929-45a9-b02b-1f0265c881e1.png)

My specs:
- CSP 0.1.79-preview5
- Pure 0.102 
- NVIDIA GTX 1080Ti using 511.79 driver, Intel i7-7700K
- HP Reverb G2, using standard SteamVR
- FSR, VRS disabled (obviously)

**Comment by gro-ove** [comment]
Should be fixed now, I hope, sorry for taking so long
