### ISSUE TITLE
[PARTICLES FX] Realism in sparks behavior (1985-1994 F1 cars)

### ISSUE THREAD

**Issue by disquettes83** [ac-custom-shaders-patch/acc-extension-config#291]
I'm always trying to make the sparks look as realistic as possible. Is there any way to tweak the code more deeply than what can be done in the particles_fx.ini file?
For instance, I wonder if there is any way to add some sort of "turbulence".

I noticed that there was nice randomness to the particles floating in the air (img1) that I don't seem to see anymore after the 1.79p5 update. Those that last the longest now all remain on the ground (img2). Changing the lifespan parameters does not seem to affect it.
In my opinion, it is good to have sparks remaining on the ground, and it would be also good to see more sparks floating in the air.

![img1](https://user-images.githubusercontent.com/29695586/175248438-13f03f7b-2a67-4a5e-ba54-24e2e6a1c781.png)
![img2](https://user-images.githubusercontent.com/29695586/175248464-17035f14-de56-419c-8efa-42327497fed6.png)

Thank you very much.

**Comment by Trava715** [comment]
Already mentioned in #180, no response.
