### ISSUE TITLE
got 'Unexpected character encountered while parsing value:.Path",line 0,position 0' error in patch menu

### ISSUE THREAD

**Issue by wyapples** [ac-custom-shaders-patch/acc-extension-config#297]
I don't know when to start. Except for the update column in the patch menu, other columns will show errors as shown in the figure.I reinstalled the game, CM launcher, CSP, sol, but it didn't work.

![mmexport1657300210085.png](https://user-images.githubusercontent.com/1128496/178038876-33df7858-92be-41b9-944d-b84076a7a048.png)

**Comment by Trava715** [comment]
1. Not a CSP issue
2. One of x4fab's servers seems to be down
