### ISSUE TITLE
Graphical issue with Shuto Expressway

### ISSUE THREAD

**Issue by gilbertohasnofb** [ac-custom-shaders-patch/acc-extension-config#30]
I am having an issue with CSP and the original Shuto Expressway track (not the Shuto Revival Project). When I enable shadders patch I get a black object near the horizon (see screenshot below). I also installed the Shuto C1 Midnight version of the same track, and that one works without a problem. Disabling the custom shaders (or more specifically, just the Weather FX active button) in my Content Manager settings makes the issue go away.

![image](https://user-images.githubusercontent.com/5700795/77578587-b492e480-6ed0-11ea-841b-2328fef6c28c.png)

PS: apologies if this is the incorrect place to be reporting this bug.

**Comment by gro-ove** [comment]
Could you please send me a link to the track? Or, if it’s not available, please give me the name of the folder and the name of that black object (there is now a new Object Inspector app in AC to check it quickly).

**Comment by gilbertohasnofb** [comment]
Sure, this is the track: https://assettocorsa.club/mods/tracks/shuto-expressway-c1.html

**Comment by gro-ove** [comment]
Thanks, pushed a new config. Let me know if it works now

**Comment by gilbertohasnofb** [comment]
Yes it does! Thank you _so much_ for the quick fix, I really appreciate it!

**Comment by gro-ove** [comment]
Glad to help, thanks for the report! :)

**Comment by gilbertohasnofb** [comment]
No sorry, I spoke too soon:

![image](https://user-images.githubusercontent.com/5700795/77596317-9a1e3280-6ef3-11ea-8f2e-f61cb81bddaa.png)

It seems that the black object behind the start line of the Inner circuit layout has been fixed, but there seems to be other ones around the track as seen above. There is the back view from the start line with the fixed object (compare to my first screenshot in the original post):

![image](https://user-images.githubusercontent.com/5700795/77596407-d0f44880-6ef3-11ea-93db-1f1910d95770.png)

**Comment by gro-ove** [comment]
Oh, ok, will fix a bit later. A couple of new nasty problems popped up. 😬

**Comment by gilbertohasnofb** [comment]
No worries at all, thanks for taking a look at this once again.

**Comment by gilbertohasnofb** [comment]
@gro-ove When you take another look at this, could you check if you can reproduce another small bug. Whenever I drive through one of the many tunnels in the track there are some strange black flickering in the car and walls. This is not present when I disable CSP. Even if I park the car in the tunnels, the flickering continues, which makes me think this is not due to shadows. There is a tunnel around 20-30 seconds into the Inner layout if you'd like to take a look at it. I tried taking screenshots but it's a bit difficult to catch these flickers; but if you open both images side by side and switch between them, you can see that the first one has a weird black shadow on the car while the second doesn't, even though the car hasn't move between the images. Again, this flickering is very fast, happening for just one frame every second or so. It also affects the tunnel itself and the track outside the tunnel from that position, even though the screenshots did not capture this. But once out of the tunnel, the flickering completely stops. 

![image](https://user-images.githubusercontent.com/5700795/77600974-5b8f7480-6f01-11ea-83e0-b9115b91b858.png)

![image](https://user-images.githubusercontent.com/5700795/77600978-60542880-6f01-11ea-9cc9-59516e9e41eb.png)

**Comment by gilbertohasnofb** [comment]
@gro-ove apologies for bumping this but were you able to reproduce the bugs?

**Comment by RustyChest** [comment]
@gilbertohasnofb This is an issue with your SOL install. The config is not on GitHub and thus cannot be fixed by us @gro-ove , please do not further modify SRP bugs and read the instructions for installing the track.

**Comment by gilbertohasnofb** [comment]
@RustyChest Perhaps the second issue might be only on my side, but @gro-ove was clearly able to reproduce the main one (the black  'billboards' in the horizon), and was also able to partially fix it. I suspect those are multiple objects and that he fixed a single one, which was the one visible from the start line. If that's the case, then it's a pity this issue is being closed, as there seem to be a fix to this. I understand that this track is a bit older (last release was on mid 2016), but unfortunately my PC cannot handle the Revival Project version.
