### ISSUE TITLE
[RAIN FX] CSP rain tires overheating.

### ISSUE THREAD

**Issue by chas1723** [ac-custom-shaders-patch/acc-extension-config#302]
![Screenshot 2022-07-30 162115](https://user-images.githubusercontent.com/92643911/181995173-3ab0caba-85d9-4e57-ae9c-5b8fb4400024.jpg)

I am currently on 1.79 preview32 and am having problems with CSP generated rain tires.  This has been an issue throughout 1.79 but I am not sure when it exactly started.  Any CSP generated rain tires will overheat just accelerating down a strait.  If you go into a hard turn, it is possible to pop the tires.  The picture I posted is just about 4 laps around silverstone with a normal amount of rain coming down.  I have not spun and as you can tell by times, I am not pushing hard at all.  This also happens with F1 cars but much more extreme due to the high load on the tires.

**Comment by CheesyManiac** [comment]
Tested and I am able to confirm. 

On CSP versions 2072 (1.79p25) and below I cannot replicate this behaviour in any car. 

However on CSP 2076 (1.79p29) and onwards this is easy to create, and happens simply by driving in a straight line.

This occurs both offline and in online servers with "Extended physics" enabled.

Definitely a regression.

**Comment by chas1723** [comment]
I can confirm now that it is p29 and up.  earlier versions of 1.79 do not show this behavior.

**Comment by chas1723** [comment]
this appears to be fixed on 1.80p1 so I am closing the issue.
