### ISSUE TITLE
Graphical issue with Croft Circuit - Flags Broken

### ISSUE THREAD

**Issue by norms360** [ac-custom-shaders-patch/acc-extension-config#31]
The 2 newest versions of CSP as of writing this break the flags on Croft Circuit.  Version 1.48 and prior do not have this problem.  The track is available from RD https://www.racedepartment.com/downloads/croft-circuit.16806/

CSP 1.48 and earlier:

![croft_csp1_48](https://user-images.githubusercontent.com/808373/77642843-37aa4e00-6f56-11ea-8440-bdf002703cb9.jpg)

CSP 1.49 & 1.50:

![croft_csp1_50](https://user-images.githubusercontent.com/808373/77642855-3b3dd500-6f56-11ea-8549-848ac759080d.jpg)

**Comment by gro-ove** [comment]
Oh, nice, I can reproduce it on this track! Will fix.

**Comment by norms360** [comment]
Issue resolved, many thanks!
