### ISSUE TITLE
Encrypted car

### ISSUE THREAD

**Issue by echokraken11** [ac-custom-shaders-patch/acc-extension-config#311]
Im sorry i know this isnt a page for this, but i need little help.
i want some cars to work in showroom,
![image](https://user-images.githubusercontent.com/99920778/189479943-c637ed4a-f338-4fe6-b908-683d40c48196.png)
some cars looks like this in showroom or some doesnt even show, i just want to get screenshots for a car. 
PLease help

**Comment by Marocco2** [comment]
Some authors won't make their car work on CM showroom by design. You can still try AC showroom with latest (Patreon?) patches
