### ISSUE TITLE
Refractions broken with rain on 0.1.79-preview72 and newer

### ISSUE THREAD

**Issue by ciba1991** [ac-custom-shaders-patch/acc-extension-config#315]
Having any rain parameter higher than 0, breaks refracted lights. It is most visible at night. Issue appeared in 79 preview 72, preview 70 worked fine.
preview 70
![preview70](https://user-images.githubusercontent.com/27741236/197115367-c2b683a1-47da-44f5-8e70-5be808ef067f.png)

preview 72
![preview72](https://user-images.githubusercontent.com/27741236/197115410-3199cca9-0855-4c8f-b2c3-8d0a226a6372.png)

**Comment by ciba1991** [comment]
Found culprit, issue only occurs if dynamic shadows in lightingFx is enabled

**Comment by Vannipo** [comment]
![image](https://user-images.githubusercontent.com/76270473/197162588-3b191b47-f8e0-4a32-8f37-3d50bdde5fd7.png)
![image](https://user-images.githubusercontent.com/76270473/197162627-26f98ae0-1040-4f3c-b9ad-45ae8d9fe0dd.png)

**Comment by H4rdas** [comment]
I'm encountering this issue aswell, except turning off Dynamic shadows on CSP 1.80p1 doesn't help

![image](https://user-images.githubusercontent.com/97806736/198681780-bb83e67c-57a2-4556-b02a-6b65b6a9dda6.png)

**Comment by coyotezin** [comment]
From what i was testing, what is doing this is ```Inner spec. exp.```
Maybe this parameter is broken or something changed on how this is affected by rain

Tested on **CSP 1.80p1**, this issue didnt exist in previous version
https://streamable.com/151n3p

**Comment by ciba1991** [comment]
> 
Do note that dynamic shadows cannot be toggled while ingame. Changing the setting requires a restart.

**Comment by ciba1991** [comment]
Issue fixed in 0.1.80p46
