### ISSUE TITLE
Can't see "Creator tools"

### ISSUE THREAD

**Issue by T0M40WS4Y** [ac-custom-shaders-patch/acc-extension-config#319]
![image](https://user-images.githubusercontent.com/95720045/198881492-73599cf0-a575-4eb6-8816-fce53dd41bcc.png)
I don't have these options 
![image](https://user-images.githubusercontent.com/95720045/198881502-5fb5ddb5-a7f3-4407-bc8e-eebbdbe29147.png)

**Comment by CheesyManiac** [comment]
Not an issue. Don't use CSP issue page for CM questions, and perhaps join the [Discord](https://discord.gg/YsnGnn2T) instead.

Update content manager from the latest release
https://github.com/gro-ove/actools/tree/v0.8.2467.39678
