### ISSUE TITLE
GPU May be overheating or overclocked - DXGI flip mode is disabled

### ISSUE THREAD

**Issue by k41zen** [ac-custom-shaders-patch/acc-extension-config#32]
Experiencing this issue now for weeks with 0.1.46 (which was working very well for me). Upgraded to 0.1.50 and now tried 0.1.51. Tried all things in discord channel (this being one of them) but nothing works apart from disabling all extensions in CM. 

I'm shown sat in the car with a single frozen image in front of me with a black surround all around me. This is exactly the same if I launch the game from AC natively but after 10-20 of looking around I see the error "unexpected error try reinstalling CSP". If I launch the game from CM I see the same issue but as soon as I turn my head AC crashes and I see the GPU overheated error. 

Have deleted AC folder structure and removed game from Steam. Have deleted entire \Documents\AC folder and \AppData\AC content manager and started again many times - still the same issue.

Running an i7-9700 OC'd to 5GHz, 2080ti, 16GB RAM, Valve Index.

All other games (iRacing, R3E, PC2, AMS, AMS3, ACC) work fine. AC is now for some reason the only one that crashes.

Please help.

**Comment by RustyChest** [comment]
This is a bit of an old post, sorry it took so long to get to you. 
If you could provide logs appropriate to the time period when this issue happened I could assist you further.
You can find the necessary logs under Documents/Assetto Corsa/logs/crash_report.zip, in this case you should sort by date and find one corresponding to this particular date.
