### ISSUE TITLE
Every Version after recommend will cause hard pc crash

### ISSUE THREAD

**Issue by vickersnm** [ac-custom-shaders-patch/acc-extension-config#323]
Not sure where to talk about this.  Found a few posts but not sure if mine is related.  All the F1 mods require a version of csp higher than recommend.  My issue is they all hard crash my pc in seconds.  I launch into a game fine but once i hit drive (sometimes in the pit) the pc hard crashes.  With out CSP or using the recommend level this does not happen at all.  I saw a post on possible replay and tried turning all that down and off and still no luck.  I'm trying to get 1.76 to work but nothing above it works either.

If there are logs I can send I will be happy too.  I looked in the AC logs and didn't see anything there pointing to the crash.

**Comment by Trava715** [comment]
This is user config issue, not a bug report. Post in CSP discord in the #troubleshooting channel.
