### ISSUE TITLE
Bind Sound to a Mesh

### ISSUE THREAD

**Issue by RobPawn** [ac-custom-shaders-patch/acc-extension-config#325]
Hey there, thanks for your great work.

i just miss how it is possible to bind sounds to a mesh.
i do not find any information about, how you could fix sound to the train you showed us in the "Animated Track Objects" video.

in my case its not even nessesary to follow a animation, its just for having sound on a position in one layout of the track but not on another (at the same location in race layout i need the sound whereas in freeroam layout there shouldn't be the sound)

by using "position =" in the ext-config i would have the sound on both layouts.

Greetz

**Comment by Marocco2** [comment]
Head to CSP discord for config support:
https://discord.gg/fDCnj3cY
