### ISSUE TITLE
BrakeFX glow effect broken

### ISSUE THREAD

**Issue by chas1723** [ac-custom-shaders-patch/acc-extension-config#330]
as of 1.79 and into 1.80, BrakeFX seems to be broken.  The brakes no longer glow under braking if there is a BrakeFX entry in the config.ini file.  The only thing you get it the glow on the ground.  Prior to 1.79, it appears to work correctly.  If you set BrakeFX to ACTIVE=0 they glow as they should.
![Screenshot 2022-11-21 235745](https://user-images.githubusercontent.com/92643911/203225379-1a9391f0-b26d-4af3-839d-b1eb661a75cb.jpg)

**Comment by chas1723** [comment]
as an update, it seems to affect URD cars the most

**Comment by Marocco2** [comment]
> as an update, it seems to affect URD cars the most

Config issue? Check other cars please

**Comment by chas1723** [comment]
some pessio cars also exhibit this.  It works fine a couple of csp releases back.  I am wondering if it is related issue #270

**Comment by Marocco2** [comment]
Should be fixed in latest CSP previews, closing
