### ISSUE TITLE
[Linux/Proton/Wine] "Failed to find a DualSense controller." with CSP 0.1.80-preview108.

### ISSUE THREAD

**Issue by TonySSS100** [ac-custom-shaders-patch/acc-extension-config#336]
So when I installed latest CSP version yesterday, I loaded up the game with PS5 controller connected by USB, CM recognized it with its proper name and all controls work fine, when I started a session, I get this message:
![Screenshot from 2022-12-25 04-34-20](https://user-images.githubusercontent.com/37266535/209470389-cfc82694-77f7-45fd-b4f7-f5d61b3a0b48.png)

I tried disabling Steam Input, but that didn't made CSP recognize it still, although it does work normally if I were to use it as wheel and map all buttons and axis to it, just with out extensions for it. Is it perhaps a new Wine issue towards CSP?

Also, Merry Xmas.

**Comment by Marocco2** [comment]
I don't think CM is capable of intercepting DS4 inputs inside Wine. I hope I'm wrong

**Comment by TonySSS100** [comment]
Please close this, DualSense works properly once I installed GE-Proton7-42 via ProtonUp-Qt to Steam and applied it to AC, along with CM stuff like showroom, presets and car selection icons also working properly as well.
