### ISSUE TITLE
gt86 no dashboard backlight

### ISSUE THREAD

**Issue by xeron** [ac-custom-shaders-patch/acc-extension-config#34]
Kunos GT86 no instruments backlight. This makes instruments unusable during the night.

Removing custom config fixes the issue.

Removing the following from the config also fixes the issue:
```
[CustomEmissive]
Meshes = INT_display_A
Resolution = 1024, 512
AreasSubtractive = 1
@ = CustomEmissive_AreaMask, Start = "28, 125", Size = "334, 334", CornerRadius = 1, Exponent = 0.3
@ = CustomEmissive_AreaMask, Start = "667, 114", Size = "330, 326", CornerRadius = 1, Exponent = 0.3
@ = CustomEmissive_AreaMask, Start = "331, 40", Size = "369, 369", CornerRadius = 1, Exponent = 0.3
```

Patch version is 1.46. Mostly default installation, only SOL reinstalled manually according to their installation manual.

Tested other random Kunos car (rx7) and dash backlight works fine.

@gro-ove looks lile you've added this recently, could you please take a look?

**Comment by xeron** [comment]
Also looks like it works with patch v1.52.

**Comment by zerobandwidth** [comment]
Just confirmed that this is working by simply upgrading to v0.1.52 of CSP.
Recommend CSP upgrade as workaround, as that is the latest "relatively functional" version.
Recommend closure of this issue.

**Comment by RustyChest** [comment]
This specific use of Custom Emissives requires patch version 1.49 or above. I will ask x4 about raising the stable branch to 1.52.
