### ISSUE TITLE
dark anomaly showing up since 1.80p115

### ISSUE THREAD

**Issue by chas1723** [ac-custom-shaders-patch/acc-extension-config#340]
https://youtu.be/nxpm4W_QAHc

if you watch at the corkscrew on the right side of the car you will notice it flickers dark.  I have noticed this on several tracks with several different cars.

It seems if I disable extended physics it goes away.  I have tried all the different options in the general patch settings/physics tweaks.  nothing has gotten rid of it other than disabling extended physics.

**Comment by Marocco2** [comment]
Seems like fake car shadows are being lied by new tyre contact patch, resulting in this glitch

**Comment by chas1723** [comment]
it does not matter if Fake Shadows are on or off.  It still does it.  Only when extended physics is turned off, does it go away.

**Comment by ludwig6666** [comment]
https://youtu.be/BWDeMfs01rg -> here it's clearer. 

It only happens when extended physics (EP) are enabled. This happend when tyres gets completely separated from the asphalt.

Same car, same turn, same velocity with EP the car floats  generating a separation betwen tyres and road generating this "black shadow"

**Comment by chas1723** [comment]
I will agree with ludwig.  I loaded up Nords with a car with very stiff suspension and when the car bounced, this dark thing happened every time the tires came off the ground.  when both front tires left the ground the whole view out the front window darkened.  if it is just one side of the car, it only happens on that side.  does not happen without extended physics enabled.

**Comment by chas1723** [comment]
this has been fixed it seems with 1.80p150
