### ISSUE TITLE
Real Mirrors - Stereo reflections in VR - stops working in 0.1.80-preview115

### ISSUE THREAD

**Issue by ludwig6666** [ac-custom-shaders-patch/acc-extension-config#342]
in VR It just render 1 eye.

I've tried:

-2 diferents headsets
-with and without Single Pass Stereo
-with and without OpenComposite
-with and without performance tweaks in smart mirrors (0 to 3 frames)

applying all those combinations still doesn't work in any case.

**Comment by Marocco2** [comment]
Do you know the latest working CSP patch with this enabled?

**Comment by ludwig6666** [comment]
0.1.80-preview1 it works

**Comment by YacobDoodjack** [comment]
It works on 1.80p108 too.

**Comment by Wanderkroete** [comment]
I have the same issue and I downgraded to the previous version (1.80p108) too. For me, the stereo reflection are THE feature, that make VR assetto stand out of any other racing games. It adds such a big part in immersion, that it makes me really sad to not have it, to the point, that I don't wanna drive anymore.
I hope it will be fixed!

**Comment by Dudel22** [comment]
I also hope that such an important feature for VR will be fixed as soon as possible!

**Comment by Wanderkroete** [comment]
I think this is a good time to start praying for the first time in my life

**Comment by ludwig6666** [comment]
still not working on 0.1.80-preview218  :-(

**Comment by Wanderkroete** [comment]
Very sad

**Comment by pastrioccio** [comment]
Found the solution:  Go to setting, assetto corsa, video - mirrors, and disable "High quality" it work for me with mirror resolution max too!

**Comment by ludwig6666** [comment]
> Found the solution:  Go to setting, assetto corsa, video - mirrors, and disable "High quality" it work for me with mirror resolution max too!

unbelievable but true, it works! Quite a workaround! Thanks for sharing 👍👍👍

**Comment by Wanderkroete** [comment]
Wow amazing.. you are right.... i could swear I tried that with the previous version. But I'm not sure anymore, and too lazy to try... it works! Not sure though about the quality difference even at highest resolution 🤔

**Comment by burnie101** [comment]
> Found the solution: Go to setting, assetto corsa, video - mirrors, and disable "High quality" it work for me with mirror resolution max too!

Thanks for the workaround. Really glad there is a way to kind of fix the mirrors. However,  I have noticed some issues with having "high quality" unchecked.

If the driver has a helmet, the visor isn't rendered in the mirror reflection and if the car has a rear windshield, raindrops aren't rendered on the glass in the reflection.

Hope it gets fixed eventually.

**Comment by maxsteep** [comment]
Personally this and the single stereo pass culling too much on edges of periphery are the worst offenders for immersion

Unchecking high quality mirror is a 'tragedy' to resort to

**Comment by ludwig6666** [comment]
fixed in 0.1.8.0 preview346
