### ISSUE TITLE
Baking/compiling doesn't seem to work

### ISSUE THREAD

**Issue by wmialil** [ac-custom-shaders-patch/acc-extension-config#344]
@gro-ove 

Every time I try to bake the trees I get an error ("failed to extract list of procedural trees")

Have tried all sorts of different things - AC root folder in different places, simple fbx single plane with 1 procedural tree on it, aligned trees/unaligned trees, no baking in VAO params, just compile = 1, etc.

Using latest version of optix bakery and with an RTX/CUDA GPU (3070) Perhaps it is just not functional at the moment? I have not seen any other tracks with a compiled list yet.

![extractTreesFail](https://user-images.githubusercontent.com/65859089/211690693-966b805a-d0c8-4259-b4f3-639b59ca4674.jpg)

**Comment by tombon12** [comment]
+1
I'm experiencing the same issue using an RTX 3080

**Comment by Marocco2** [comment]
The right place to post this issue is here:
https://github.com/ac-custom-shaders-patch/acc-bakeryoptix
