### ISSUE TITLE
Ferrari 488 GT3 Rear view monitor dim and flipped

### ISSUE THREAD

**Issue by matthew-nm** [ac-custom-shaders-patch/acc-extension-config#351]
I have CSP 0.1.79 installed, and I'm not sure if this is new or I'm just noticing this bug with this car (Ferrari 488 GT3), but the rear view digital display in the cockpit is very dim and backwards. The text appears forwards, but the image of the world behind is *not* flipped like a real mirror so the cars pass on the wrong side. Also, it's so dim I can barely see the image.

Is this a CSP bug?

I have a triple monitor setup and this is a cropped image from a side monitor.

![488_mirror_issue](https://user-images.githubusercontent.com/5170156/216125594-b7c9e007-b22c-4c77-9eee-3cd405f7ac38.png)

I can see from the .ini file ([488_gt3.ini](https://github.com/ac-custom-shaders-patch/acc-extension-config/blob/master/config/cars/kunos/ks_ferrari_488_gt3.ini)) that the mirror is replaced by a custom mirror shader with buttons and whatnot. I can confirm that the buttons work, but the rearward image is flipped and everything is very dim.

I think this may be two separate things. One is the flipped issue as seen here (#137), and another is simply that the display filters are too dim. I've noticed this when turning my side mirrors into monitors (using the Real Mirrors config in-game) and applying the display filters.

Ultimately solving the issue would be nice, but I am content to remove the custom mirror for now. I have updated my local .ini file (extension/config/cars/loaded/...ini) and removed the custom mirror section to get back to the original implementation which works fine.

**Comment by CheesyManiac** [comment]
This is related to the shader used on the display, I am working on updating the script used and will push a fix in the near future. It is not a problem with CSP directly, but instead outdated config.

**Comment by Marocco2** [comment]
Fixed by new config
