### ISSUE TITLE
question regardin these extension on my server

### ISSUE THREAD

**Issue by Makarovmw2** [ac-custom-shaders-patch/acc-extension-config#353]
i copy some of these extension on my server but they seem to not work, for example the wrong way code and the custom color
![Desktop Screenshot 2023 02 03 - 18 51 59 66](https://user-images.githubusercontent.com/112247964/216675593-4a946836-16be-439e-9215-abf886e3c296.png)

**Comment by CheesyManiac** [comment]
None of that is correctly formatted. This is not an issue with CSP.

Please join the CSP discord for futher help:
https://discord.gg/SWryb5V

**Comment by Makarovmw2** [comment]
Where should i write the problem?
