### ISSUE TITLE
Problems with the Tree Model Converter

### ISSUE THREAD

**Issue by justkauser** [ac-custom-shaders-patch/acc-extension-config#361]
I implemented a simple model of a conifer with Blender and exported it in different LOD levels. I can only convert the LOD0 to a .Bin. With the other two LODs I get an error message that the folder cannot be accessed. It's probably my fault, but wouldn't it be more convenient for the community to write an editor that converts kn5 objects into the bin files, considering that the code for converting kn5 to fbx is already implemented in the Custom Showroom ? I don't know if Blender is the problem, but so far I haven't had any problems creating kn5 using Kuno's ksEditor.
[Tanne fbx files.zip](https://github.com/ac-custom-shaders-patch/acc-extension-config/files/10767499/Tanne.fbx.files.zip)

**Comment by justkauser** [comment]
Ok, i found my problem, i messed up the materials. It works for now. But what confuses me is that I don't export an fbx for the individual LOD.bin files as in the wiki, but each LOD individually in an fbx. Did I do something wrong or is the WIKI info wrong. I took mike08's Autopolis version as a template and looked at the zip file there, where each LOD has a single bin file.
[tree0.zip](https://github.com/ac-custom-shaders-patch/acc-extension-config/files/10767678/tree0.zip)

**Comment by CheesyManiac** [comment]
For future reference, questions such as these should be in the CSP Discord: https://discord.gg/SWryb5V
