### ISSUE TITLE
Can't generate previews using vanilla showroom on Linux with Proton

### ISSUE THREAD

**Issue by TonySSS100** [ac-custom-shaders-patch/acc-extension-config#391]
I'm liking this CSP preview a lot, save for some bugs such as random crashes when I start a race and certain tracks having broken lights at night such as Monza.

Another bug has to exclusively do with Proton on Linux since it's about generating car previews using vanilla showroom with CSP instead of CM one. It gives me DLL errors about D3D, similar to an older bug months ago where It wasn't possible to launch the game at all with CSP active:

00000003AF6DB008 (ucrtbase): (filename not available): strrchr
00000001C889B8E7 (d3dcompiler_47): (filename not available): D3DWriteBlobToFile
00000001C889B3AD (d3dcompiler_47): (filename not available): D3DWriteBlobToFile
00000002FCABCC13 (libvkd3d-shader-1): (filename not available): vkd3d_shader_compile
00000001C889D193 (d3dcompiler_47): (filename not available): D3DCompile2
00000001C889D60E (d3dcompiler_47): (filename not available): D3DCompile
AC\cubemaprenderer.cpp (79): CubeMapRenderer::render
AC\cameraforwardyebis.cpp (1177): CameraForwardYebis::render
AC\sim.cpp (2564): Sim::renderScene
AC\game.cpp (275): Game::render
AC\game.cpp (275): Game::render
AC\game.cpp (275): Game::render
AC\game.cpp (126): Game::onIdle
AC\game.cpp (210): Game::run
AC\acs.cpp (477): wWinMain
f:\dd\vctools\crt\crtw32\dllstuff\crtexe.c (618): __tmainCRTStartup
000000007B62CDA9 (kernel32): (filename not available): BaseThreadInitThunk
000000017005FF37 (ntdll): (filename not available): RtlUserThreadStart

**Comment by Marocco2** [comment]
Isn't this a CM issue?

**Comment by TonySSS100** [comment]
UPDATE: installing latest version of GE-Proton solved that issue, now I can use CSP showroom to generate previews without any issues anymore thankfully.
