### ISSUE TITLE
Interesting conflict with car body and CustomEmissive

### ISSUE THREAD

**Issue by zerobandwidth** [ac-custom-shaders-patch/acc-extension-config#40]
This is an interesting issue that I've recently run into while working on a car livery where we wanted to selectively light up regions of the main body.

Whenever you apply a `CustomEmissive` directive to a mesh, its shader is changed to `ksPerPixelMultiMap_emissive`, which works just fine... unless you're working on the main body parts that are supposed to show dirt and damage. Those body parts generally use the `ksPerPixelMultiMap_damage_dirt` shader instead. This shader uses a specific type of "damage-shaded" normal map texture in the same slot (`txNormal`) that is usually "flat".

This turns out to produce a conflict when trying to do `CustomEmissive`s.

* If you just have the `CustomEmissive` directive, then the `txNormal` used by the `ksPerPixelMultiMap_emissive` shader is the "damage-shaded" one, and so your car will always look damaged, even when it's not.
* If you use a `SHADER_REPLACEMENT` directive to try to substitute the flat normal map, then the lighting works, but now the car _never_ shows damage, even when it's... well, damaged. Nor does it ever get dirty. This happens regardless of which shader you try to make happy in the directive.
* If you modify both the `CustomEmissive` and `SHADER_REPLACEMENT` sections to use the `ksPerPixelMultiMap_damage_dirt` directives, then you lose the masking effects of the `CustomEmissive`. The body glows with the colors you specifed, but isn't masked; the whole mesh glows.

So it seems, in order to have both capabilities in play (damage/dirt modelling AND selective masking of emissive regions), we'd need a new shader that is capable of filling both roles. It might have a resource list similar to the following:
* `txDiffuse` - applies to both
* `txNormal` - as used by `_emissive` and other shaders, the "clean" normal map
* `txMaps` - applies to both
* `txDetail` - applies to both
* `txEmissive` - as used by `_emissive` shader
* `txDamage` - as used by `_damage_dirt` shader
* `txDamageNormal` - new resource to play the role of the "damaged" normal map expected by `_damage_dirt` shader
* `txDust` - as used by `_damage_dirt` shader
* `txDamageMask` - as used by `_damage_dirt` shader
This seems way outside my current experience with CSP and its inner workings, and might be entirely wrong.

The "meh" workaround is to choose the middle of the three approaches above: Construct the `CustomEmissive` the way you want it, then construct a `SHADER_REPLACEMENT` to restore the stack of texture resources, substituting a flat normal map for the damage-shaded one. This allows the lighting to work but completely disables damage/dirt rendering for the affected meshes.

Thanks to Crash and @RustyChest for helping me stumble this far in the investigation.

Wheeeeeee, learning! 😆

**Comment by zerobandwidth** [comment]
🤔 💭 Since it's unlikely this will be solvable without creating a new shader, maybe it would be best to simply document this pitfall on the [Multichannel Emissives](https://github.com/ac-custom-shaders-patch/acc-extension-config/wiki/Cars-%E2%80%93-Multichannel-emissives) page on the wiki and close this issue, in favor of a roadmap item for the shaders repo...?

**Comment by Trava715** [comment]
Not possible for now, best workaround is using MultiMap_Emissive_AT, make overlay mesh(es) on top of car body and manage them with kn5 replacement HIDE= function.

**Comment by RustyChest** [comment]
Closed due to inactivity
