### ISSUE TITLE
Server extra options: FORCE_HEADLIGHTS parameter doesn't work

### ISSUE THREAD

**Issue by bandrefilipe** [ac-custom-shaders-patch/acc-extension-config#402]
The `FORCE_HEADLIGHTS=1` parameter, like stated [here](https://github.com/ac-custom-shaders-patch/acc-extension-config/wiki/Misc-%E2%80%93-Server-extra-options#other-online-tweaks) seems to do nothing.

The `ENTRY LIST > CSP > Force headlights` option does work, but it's somewhat inconvenient.

I'm running CM `0.8.2561.39678 (x86)`, CSP `0.1.80-preview218`

**Comment by CheesyManiac** [comment]
How are you testing this?
What is your extra options config?

That option only forces lights on for other player cars. It does not prevent you from turning off your own lights. If you do turn off your lights, they're only off for you, others will still see them on

**Comment by bandrefilipe** [comment]
Oh, I thought its behavior was like the `ENTRY LIST > CSP > Force headlights` one. Thanks!
