### ISSUE TITLE
car texture dont load in properly due to CSP issues

### ISSUE THREAD

**Issue by saucydemon** [ac-custom-shaders-patch/acc-extension-config#404]
https://cdn.discordapp.com/attachments/805958856126758922/1126796193238896711/image.png
https://cdn.discordapp.com/attachments/805958856126758922/1126796258162520095/image.png

As provided with the pictures above thats my issue every time i try use the 911 that error pops up i have made sure im using the latest CSP version 1.79. and nothing works when i click yes thats what it looks like i can still drive the car as normal it just looks like that.

**Comment by CheesyManiac** [comment]
Please join the CSP Discord for content issues
https://discord.gg/nM4Xkrt

The github is for confirmed bugs. Failed model decryption more likely an issue with the car, not CSP.
