### ISSUE TITLE
[Linux/Proton] Black sky with weatherFx enabled

### ISSUE THREAD

**Issue by tim-gromeyer** [ac-custom-shaders-patch/acc-extension-config#407]
Hello :)

When I enable weatherFx, I have a black sky. I tried to disable all options in weatherFx and I tried every weather script (Default, Sol)

I'm using version 1.78 because of #316 and I can't use the preview version where it's fixed because I don't have patreon

**Comment by RustyChest** [comment]
Hey Tim, I'll be happy to assist you.

Could you provide us with the most recent "custom_shaders_patch.log" and "log.txt" from the Documents folder so we can investigate if there's any funny business wherein the textures aren't being properly loaded?

Also, while we're at it, could you try deleting your Documents\Assetto Corsa\cfg\extension\weather_fx.ini to set everything back to default?

**Comment by tim-gromeyer** [comment]
Thanks for your help, but somehow it works now... I have not changed anything. I set up my system from scratch. I use the same version of Proton, a backup of the prefix (the windows folder, including the settings) and yet it somehow works.

**Comment by tim-gromeyer** [comment]
Thanks for your help, but somehow it works now... I have not changed anything. I set up my system from scratch. I use the same version of Proton, a backup of the prefix (the windows folder, including the settings) and yet it somehow works.
