### ISSUE TITLE
[PITS_SPEED_LIMITER]SPEED_KMH will cause car loss KERS/ERS power

### ISSUE THREAD

**Issue by kagurazakayukari** [ac-custom-shaders-patch/acc-extension-config#410]
Hello devs, 

Recently I launched some servers with a pitlane speed limit of 60km/h, and I found KERS/ERS will not operate correctly on certain hybrid cars. The acceleration process is purely achieved by ICE. Does it because the lacking of CM extends physics or other reasons or simply a bug?

**Comment by kagurazakayukari** [comment]
I've also got a video to show this.
The car in the video is a modified mod with the ability to produce ERS power after 190km/h.
On the first try, the pit speed limiter is limited to 60km/h on the server. After the pit exit the car is unable to normally speed up when after 190km/h.
On the second try, the pit speed limiter in the CSP config was deleted on the server. After the pit exit the car is speed up normally when after 190km/h.

 https://youtu.be/AFNe9rvfZiU

**Comment by CheesyManiac** [comment]
This has been a bug for quite a while (1.78, iirc?) I'll forward it on again
