### ISSUE TITLE
[Linux|Proton] Content Manager crashes every time I open it when using latest version of GE-Proton

### ISSUE THREAD

**Issue by TonySSS100** [ac-custom-shaders-patch/acc-extension-config#412]
Yesterday when I opened CM as usual via Proton on Steam, when going to car selection window, it crashes with this message:
![2023-07-23_11-40](https://github.com/ac-custom-shaders-patch/acc-extension-config/assets/37266535/f174287d-4fa7-4679-9fe8-718359a8f407)

Game works fine, it's just CM that always crashes every time I open it with that message for some reason, back then that only happened less frequently and I could've used CM without issues, now I cannot even use it at all for this problem happening with each opening.

Has anyone else who played AC on Linux with GE-Proton so far had this issue before? And how can I manage to fix it?

**Comment by Marocco2** [comment]
Check if there are any showroom images with .BMP extension and convert them to .PNG

**Comment by Marocco2** [comment]
This isn't related to CSP, so I close this issue
