### ISSUE TITLE
[Light Bounce] Bounced light not bouncing correctly in cockpit view

### ISSUE THREAD

**Issue by Haunebu52** [ac-custom-shaders-patch/acc-extension-config#426]
Maybe this is as intended, but there is a distinct difference in bounced light when in cockpit compared to other cameras. The issue arises when you are in an open cockpit car, there is an obvious lack of light bounce when racing in open topped vehicles.

Is there a workaround to properly implement light bounces when racing an open cockpit car from the interior view? 

Thanks!

**Comment by Marocco2** [comment]
Can you show some examples?

**Comment by Haunebu52** [comment]
I've attached two comparisons, and I have exaggerated light bounce in the 2nd photo so it's easier to notice.  Any onboard camera: Cockpit, Nose, Bonnet or Dash don't show light bounce but every other camera: chase cams, TV cams and Free Cam all show light bounce.  Hope this helps!

![LightBounceCSP-1](https://github.com/ac-custom-shaders-patch/acc-extension-config/assets/144299217/3500e041-1407-4540-be28-7ea8e86b5756)
![LightBounceCSP-2](https://github.com/ac-custom-shaders-patch/acc-extension-config/assets/144299217/fef19f79-54b6-4e5a-94e6-540894166a2b)

**Comment by Marocco2** [comment]
You may have extra FX disabled for first person camera. Check Extra FX settings

**Comment by CheesyManiac** [comment]
I tested on CSP 1.80p346 and p365 and light bounce is working on all cameras, including cockpit. 
![image](https://github.com/ac-custom-shaders-patch/acc-extension-config/assets/93444114/31f03729-d45e-4ae6-8e4e-ee35f73097f0)
ExtraFX Settings attached

**Comment by Haunebu52** [comment]
I have checked and double checked my ExtraFX settings, but I have nothing disabled for interior cameras. My settings are nearly identical to @CheesyManiac with the exception of Motion Blur. Is there another setting somewhere that could cause interior cameras to disable certain effects? Could it be a PPFilter setting or an ext_config.ini setting I'm overlooking?

I appreciate everyone's help, thank you.

**Comment by Haunebu52** [comment]
That actually was not me who posted images on Discord, that's a separate person who has the same issue as I do.

I am currently at work so will update this post with all the information, but I know I am using the latest CSP (v1.80p346). I'm not sure which CM I'm using so I will edit this post later this evening with that information.  Thanks!

**Comment by Haunebu52** [comment]
Sorry for the delay.

CSP: v 0.1.80-preview346
Shaders Patch Version ID: 2501
CM: v 0.8.2561.39678 

If you need any other information I would be happy to share.

**Comment by Haunebu52** [comment]
Okay so I think I was able to figure out what was causing this issue...

It's not a CSP or CM issue, it's coming from the ext_config.ini

In the ext_config.ini -

[BOUNCED_LIGHT]
CAUSTICS = 1
CAUSTICS_SCALE = 1 ; optionally, adjust caustics intensity

If either or both of these Caustics lines are in the ext_config.ini it will disable light bounce for interior cameras. 

Most tracks don't have this line, but a couple do, and I have been integrating bounced light into many tracks (bc it looks so good) and had been pasting these lines in with the other lines. If these two lines are removed, everything works properly.

Thank you for your help, and I hope this solution can assist in finding issues.
