### ISSUE TITLE
mesh adjustments wiki update

### ISSUE THREAD

**Issue by Uberbok** [ac-custom-shaders-patch/acc-extension-config#431]
car and track configs/mesh adjustments wiki page.
When trying to make all meshes with material non-renderable on track (skidmarks in this instance)

MATERIALS = some_material  ; all objects using same mat would be affected **<< Does not work**

could be replaced with:

MESHES = MATERIAL:some_material

Don't know if is same for tracks and cars!

**Comment by Marocco2** [comment]
That should be a bug of CSP as wiki states correct info AFAIK
