### ISSUE TITLE
Update wiki for server script paths

### ISSUE THREAD

**Issue by LavaToaster** [ac-custom-shaders-patch/acc-extension-config#438]
👋 Hello!

I was helping out a friend recently but spent many an hour down a rabbit hole as the relative path mentioned in the server scripts section [here](https://github.com/ac-custom-shaders-patch/acc-extension-config/wiki/Misc-%E2%80%93-Server-extra-options#online-scripts)

```
[SCRIPT_...]
SCRIPT = path  ; Path can be either a web URL: for example, you can store your script 
               ; on https://gist.github.com and use the raw link, or you can set a path
               ; relative to --------> “assettocorsa/extension/lua” <------------ for development purposes and
               ; edit scripts live.
… = …          ; Any other parameters set in this section can be accessed by the script,
               ; thus allowing to configure the same script to use with different servers.
```

Should in fact be `assettocorsa/extension/lua/online`.

Would be helpful to get this updated. Only found out about this in another [wiki](https://github.com/CheesyManiac/cheesy-lua/wiki/Dealing-with-Lua-Server-Scripts#local-debugging) that wasn't that easy to track down.

Thanks 🙏

**Comment by Marocco2** [comment]
Fixed https://github.com/ac-custom-shaders-patch/acc-extension-config/wiki/Misc-%E2%80%93-Server-extra-options
