### ISSUE TITLE
Tie Motion of Shift driver left and right for Karts to VR head lean?  

### ISSUE THREAD

**Issue by PodcastPrimate** [ac-custom-shaders-patch/acc-extension-config#439]
I've been looking around and i'm not a coder but noticing i may have to start learning how to do lua work. just wondering if you could point me in the direction of maybe callouts i should be using for any of these things to point me in the right direction. bard only got me so far and chat gpt requires me to understand things better. so i'll keep poking away but wanted to put this out there.

**Comment by Marocco2** [comment]
You can add motion leaning left or right using the same ksanim for hands when turning
