### ISSUE TITLE
replacement of edge point

### ISSUE THREAD

**Issue by VHF-ACADDICT** [ac-custom-shaders-patch/acc-extension-config#44]
https://github.com/ac-custom-shaders-patch/acc-extension-config/blob/9ed0fbbe65f6c3467d9a8dc4569a3bcfc32ff2f0/config/tracks/monza.ini#L705

should be replaced with : 

STREAM_EDGE_... = 761.5972, 4.6573, -1207.0042, 754.0655, 4.6613, -1223.5586

**Comment by adamcyan1624** [comment]
Done
