### ISSUE TITLE
Track Displays - Help from anyone that's got this to work!

### ISSUE THREAD

**Issue by Rustybrush** [ac-custom-shaders-patch/acc-extension-config#440]
Ilja,

I've been trying to get the Track Displays option working to introduce an active video screen to a track I'm currently working on - but for the life of me I cannot get my head around the information provided here on the Wiki.
I've had a look at other mods that have successfully implemented this but am still not able to get it working on mine.
I'm assuming the inputs as outlined are intended for an ext_config.ini file? I've tried a couple of iterations of this in a common folder as well as in the extension folder of the specific track skin but to no avail.
Also, it's very unclear to me in the [GENERAL] section what the list of track meshes is. Are we able to simply state a specific mesh or do we need to define a list somewhere? I've not been able to work this one out yet.
Regarding the REGION_START and REGION_SIZE parameters, what are the numbers required here? I've got a location for my display mesh via object inspector, but those are in x,y,z so I'm not sure what to input.
Sorry for the silly questions, really hoping to solve this one though! Part of the fun of modding right!!

Cheers,

Dave

**Comment by CheesyManiac** [comment]
Hi

Please join the CSP Discord for further assistance.
https://discord.gg/SWryb5V
