### ISSUE TITLE
edge point replacement

### ISSUE THREAD

**Issue by VHF-ACADDICT** [ac-custom-shaders-patch/acc-extension-config#45]
https://github.com/ac-custom-shaders-patch/acc-extension-config/blob/9ed0fbbe65f6c3467d9a8dc4569a3bcfc32ff2f0/config/tracks/monza.ini#L707

Should be replaced with : 

STREAM_EDGE_... = 607.6642, 3.8421, -694.5364, 619.3524, 3.9030, -678.9408

**Comment by adamcyan1624** [comment]
Done
