### ISSUE TITLE
Navigator in car showing blank screen

### ISSUE THREAD

**Issue by MiesThies** [ac-custom-shaders-patch/acc-extension-config#454]
As seen in the screenshot, the navigator in the M4 is blank or white. The GT3 RS' screen works fine. I cannot get it to work in the M4, though. What might be the cause, what should I try? It happens in VR and on a monitor as well.

I'm on version 0.1.80-preview115 and I have checked "Navigators for some cars" under "Car Instruments"

Content manager version is 0.8.2561.39678.

![acs_2024_03_20_16_06_43_894](https://github.com/ac-custom-shaders-patch/acc-extension-config/assets/90831279/3afd1ce8-19e6-4ee7-9f4b-ad56bbab7f77)

**Comment by CheesyManiac** [comment]
Please update CSP to 0.2 or newer and try again

**Comment by MiesThies** [comment]
It works with the newest csp version, thank you and sorry!
