### ISSUE TITLE
ks_brands_hatch.ini need a small fixes.

### ISSUE THREAD

**Issue by kolunio82** [ac-custom-shaders-patch/acc-extension-config#465]
![Assetto Corsa Screenshot 2024 07 19 - 11 06 32 21](https://github.com/user-attachments/assets/a51c944e-df6a-4e66-a19a-70194a3df860)
![Assetto Corsa Screenshot 2024 07 19 - 11 07 36 19](https://github.com/user-attachments/assets/cb247aaa-c959-4e7a-a171-3a699541793a)

One building is too bright when it rains. The roofs of the tents are also too bright.

**Comment by CheesyManiac** [comment]
You're welcome to edit the file yourself and submit a PR for us to merge

**Comment by kolunio82** [comment]
> You're welcome to edit the file yourself and submit a PR for us to merge

are you able to fix this?

**Comment by kolunio82** [comment]
[ks_brands_hatch.zip](https://github.com/user-attachments/files/16820163/ks_brands_hatch.zip)
 
you can update it
