### ISSUE TITLE
add symmons_plains, rt_lime_rock_park, fn_redbullring, pico_veleta_subida, pico_veleta_bajada, Tpa, HRT data_track_params.ini

### ISSUE THREAD

**Issue by OtxiMOU** [ac-custom-shaders-patch/acc-extension-config#467]
[symmons_plains]
NAME=Symmons Plains
LATITUDE=-41.661732
LONGITUDE=147.249971
TIMEZONE=Australia/Launcestion

[rt_lime_rock_park]
NAME=Lime Rock Park
LATITUDE=41,94444444
LONGITUDE=-73,398333
TIMEZONE=America/Lakeville

[fn_redbullring]
NAME=Red Bull Ring
HEADING_ANGLE=0
LATITUDE=47.216671
LONGITUDE=14.78333
TIMEZONE=Europe/Berlin

[pico_veleta_subida]
NAME=Pico Veleta Subida
LATITUDE=7.0749147
LONGITUDE=-3.3795373
TIMEZONE=Europe/Madrid

[pico_veleta_bajada]
NAME=Pico Veleta Bajada
LATITUDE=7.0749147
LONGITUDE=-3.3795373
TIMEZONE=Europe/Madrid

[Tpa]
NAME=Tpa
LATITUDE=42,950277
LONGITUDE=-2,381666
TIMEZONE=Europe/Madrid

[HRT]
NAME=HRT
LATITUDE=37,789722
LONGITUDE=-1,250277
TIMEZONE=Europe/Madrid

**Comment by Marocco2** [comment]
You need to make a PR and add those lines in `config/data_track_params.ini`

**Comment by OtxiMOU** [comment]
Hello, I've already done the PR, I don't know if it's right or not,
it's my first time, I still have to do something else, since I don't
see the file changed, thanks
