### ISSUE TITLE
I want to register the auto update system. but cannot contact anyone

### ISSUE THREAD

**Issue by chocolateriderx** [ac-custom-shaders-patch/acc-extension-config#472]
Hi I'm just make my own track. I want to make my track auto update but I cannot seem to be able to get response from anyone. is anyone here I can contact?

i'm follow from this link https://github.com/ac-custom-shaders-patch/acc-extension-config/wiki/Unrelated-%E2%80%93-About-content-auto-updates-system-(CUP)

**Comment by Marocco2** [comment]
You can contact him via the following socials:

Telegram: x4fab
Discord: x4fab#6636
Twitter: 0x4fab
