### ISSUE TITLE
CSP doesn't work, I can't find any solutions for the problem I'm facing online :/

### ISSUE THREAD

**Issue by SpaceEGS** [ac-custom-shaders-patch/acc-extension-config#475]
When I try to launch Assetto Corsa it keeps returning this error and I'm not sure how to fix it.
![image](https://github.com/user-attachments/assets/2d735999-8920-42fc-b094-ec79bec1651c)

**Comment by Marocco2** [comment]
Make sure you got `acs.pdb` file in your assettocorsa install folder.
Closing this issue for out of scope.
You can find support on CSP Discord server.

**Comment by CheesyManiac** [comment]
Please join the CSP Discord for further assistance.
https://discord.gg/SWryb5V
