### ISSUE TITLE
Wheels_valid_surface variable in CAI_CAR_DATA structure not working

### ISSUE THREAD

**Issue by Za9Game** [ac-custom-shaders-patch/acc-extension-config#478]
I'm having an issue with a variable in the CAI_CAR_DATA structure. I'm thinking to use the variable wheels_valid_surface to check if the car is still on track or not. But the vaule of this variable is always 0, i'm not understanding why. All the other variables works, but not this one. I suspect that the value is not being written to the shared memory. I am also analyzing it raw and those bits always remain at 0.
Version of csp that I'm using: 0.8.2686.39678

**Comment by CheesyManiac** [comment]
Hi, that version number you have quoted is the Content Manager version, not CSP.

The latest CSP is 0.2.4 aka build 3117

Please check and confirm your version, and perhaps test a roll back to 0.1.79

**Comment by Za9Game** [comment]
Yeah sorry I was using CSP 0.2.5, but even with 0.1.79 (the recommended one) I still have the same issue. So I don't think is a version problem

**Comment by Za9Game** [comment]
> Hi, that version number you have quoted is the Content Manager version, not CSP.
> 
> The latest CSP is 0.2.4 aka build 3117
> 
> Please check and confirm your version, and perhaps test a roll back to 0.1.79

Some news about it?
Mine was a project for university, but without this fix I will not be able to complete it

**Comment by Marocco2** [comment]
> > Hi, that version number you have quoted is the Content Manager version, not CSP.
> > 
> > The latest CSP is 0.2.4 aka build 3117
> > 
> > Please check and confirm your version, and perhaps test a roll back to 0.1.79
> 
> Some news about it?
> Mine was a project for university, but without this fix I will not be able to complete it

Unfortunately you'll need to wait for @gro-ove new release. We don't have any ETAs.
You can try to contact him directly via Telegram

**Comment by Marocco2** [comment]
Keeping the issue open until there is a fix available

**Comment by Za9Game** [comment]
> Keeping the issue open until there is a fix available

I fixed it with @gro-ove, it was an issue on mine Python code in the bit offset. I will share here the right struct of CAI_CAR_DATA for everyone in the future will have the same issue:

class CAI_WHEEL_DATA(ctypes.Structure):
    _pack_ = 4
    _fields_ = [
        ('position', c_float * 3),
        ('contact_point', c_float * 3),
        ('contact_normal', c_float * 3),
        ('look', c_float * 3),
        ('side', c_float * 3),
        ('velocity', c_float * 3),
        ('slip_ratio', c_float),
        ('load', c_float),
        ('pressure', c_float),
        ('angular_velocity', c_float),
        ('wear', c_float),
        ('dirty_level', c_float),
        ('core_temperature', c_float),
        ('camber_rad', c_float),
        ('disc_temperature', c_float),
        ('slip', c_float),
        ('slip_angle_deg', c_float),
        ('nd_slip', c_float)
    ]

class CAI_CAR_DATA(ctypes.Structure):
    _pack_ = 4
    _fields_ = [
        ('packet_id', c_int32),
        ('gas', c_float),
        ('brake', c_float),
        ('clutch', c_float),
        ('steer', c_float),
        ('handbrake', c_float),
        ('fuel', c_float),
        ('gear', c_int32),
        ('rpm', c_float),
        ('speed_kmh', c_float),
        ('velocity', c_float * 3),
        ('acc_g', c_float * 3),
        ('look', c_float * 3),
        ('up', c_float * 3),
        ('position', c_float * 3),
        ('local_velocity', c_float * 3),
        ('local_angular_velocity', c_float * 3),
        ('cg_height', c_float),
        ('car_damage', c_float * 5),
        ('wheels', CAI_WHEEL_DATA * 4),
        ('turbo_boost', c_float),
        ('final_ff', c_float),
        ('final_pure_ff', c_float),
        ('pit_limiter', c_bool),
        ('abs_in_action', c_bool),
        ('traction_control_in_action', c_bool),
        ('lap_time_ms', ctypes.c_uint32),
        ('best_lap_time_ms', ctypes.c_uint32),
        ('drivetrain_torque', c_float),
        ('spline_position', c_float),
        ('collision_depth', c_float),
        ('collision_counter', ctypes.c_uint32),
        ('wheels_valid_surface', ctypes.c_uint32)
    ]
