### ISSUE TITLE
replacement Monza L692 - L693

### ISSUE THREAD

**Issue by VHF-ACADDICT** [ac-custom-shaders-patch/acc-extension-config#48]
https://github.com/ac-custom-shaders-patch/acc-extension-config/blob/9ed0fbbe65f6c3467d9a8dc4569a3bcfc32ff2f0/config/tracks/monza.ini#L692

STREAM_EDGE_... = 105.0142, -2.7249, 141.8349, 80.2911, -2.7291, 139.3334

plus the following line #L693
STREAM_EDGE_... = 79.7944, -2.7179, 144.4368, 105.0180, -2.7251, 146.9376

**Comment by adamcyan1624** [comment]
Done
