### ISSUE TITLE
DOF issuewith F7 cam.

### ISSUE THREAD

**Issue by kolunio82** [ac-custom-shaders-patch/acc-extension-config#482]
Just i set f3 cam, then f7 zoom a bit and car is blurred, i opened photo app and diable blur at all, then i close photo app is blurred again. I dont know whats going on, looks like DOF issue.

https://youtu.be/JLSYV-4_pQo

**Comment by Marocco2** [comment]
Ctrl+click to the object to regain focus

**Comment by kolunio82** [comment]
you lost focus when you close photo mode app and car will be blurred

**Comment by kolunio82** [comment]
> Ctrl+click to the object to regain focus

you lost focus when you close photo mode app and car will be blurred

**Comment by Marocco2** [comment]
> > Ctrl+click to the object to regain focus
> 
> you lost focus when you close photo mode app and car will be blurred

I may assume it's intended and maybe ugly to use as default. In any case, you should switch from F1 to F7

**Comment by kolunio82** [comment]
> > > Ctrl+click to the object to regain focus
> > 
> > 
> > you lost focus when you close photo mode app and car will be blurred
> 
> I may assume it's intended and maybe ugly to use as default. In any case, you should switch from F1 to F7

press F7, zoom to car it will be blurred, open photo app and set focus, close photo app car is blurred again. i think F7 cam has error which makes car blurred
