### ISSUE TITLE
Extra info for screenshot

### ISSUE THREAD

**Issue by zuotoski** [ac-custom-shaders-patch/acc-extension-config#49]
Hi! First of all, thank you very much for all the work and resources that has been provided in CM.
This is more a question than a suggestion: Is it possible to add the PPFilter name to the file name of the screenshot ?

Thanks again and I hope that I'm not too silly.
Cheers :)

**Comment by gro-ove** [comment]
Hi, and thank you! Interesting thing, but if you’re making screenshots in JPG format (with WIC encoder, but that’s a default setting), you would get PP filter in EXIF data, and then use Windows Explorer to see it:

![20200908-171852](https://user-images.githubusercontent.com/3996502/92488575-6ad85500-f1f7-11ea-9673-73b520e72dcb.png)

And I’ll add it as a new keyword for custom format in the next update, of course, going to be `{PPFilter}`. Thanks for suggestion! 🙂

**Comment by zuotoski** [comment]
> Hi, and thank you! Interesting thing, but if you’re making screenshots in JPG format (with WIC encoder, but that’s a default setting), you would get PP filter in EXIF data, and then use Windows Explorer to see it:
> 
> ![20200908-171852](https://user-images.githubusercontent.com/3996502/92488575-6ad85500-f1f7-11ea-9673-73b520e72dcb.png)
> 
> And I’ll add it as a new keyword for custom format in the next update, of course, going to be `{PPFilter}`. Thanks for suggestion! 🙂

Hi! Thank you for the very fast replayand update.
I don't use JPEG, but PNG. Actually, the inttention to have the filter's name was purelly informative for those who see a screenshot and want to know what filter has been used (a common question in foruns and etc.) and for myself, when I want to replicate the same/near result. 
Thanks again for your fantastic contribution to the AC community.
Cheers.

**Comment by zuotoski** [comment]
Hi!
It's me, Alex, again. Just as information, is this new tag going to be available in this CSP version? I actually tried to use it with lights-patch-v0.1.63-p47 but it dind't translate the the filters' names.
No pressure, please.
Cheers.
