### ISSUE TITLE
 Where Can I Find These Programs

### ISSUE THREAD

**Issue by bayharika** [ac-custom-shaders-patch/acc-extension-config#55]
![321321321321](https://user-images.githubusercontent.com/75813019/101836788-196d9800-3b4f-11eb-8e52-0cc6020e052e.PNG)

Hello, I am interested in Assetto Corsa 3dmodels, but many people are editing my mods or playing them on their own so I want to encrypt them, but I don't know where to find the programs

**Comment by RustyChest** [comment]
You need to contact x4fab personally on Discord/Patreon
x4fab#6636
