### ISSUE TITLE
track configs: [DISPLAY_...] uses same cam for all of them

### ISSUE THREAD

**Issue by leBluem** [ac-custom-shaders-patch/acc-extension-config#56]
when using more than one 
[DISPLAY_...]
MESHES = m1
CAMERA_0 = ...
...

[DISPLAY_...]
MESHES = m2
CAMERA_0 = ...
...

Using different coodinates for each display (meshes m1, m2...) will result in the same camera to be used on each display you defined...

**Comment by Marocco2** [comment]
Still present in 0.1.76?

**Comment by gro-ove** [comment]
Seems like it might be fixed now, sorry for taking so long

![image](https://user-images.githubusercontent.com/3996502/152228914-97871c5e-80fc-4d27-8378-3a82452ba0f2.png)
