### ISSUE TITLE
Bug Report for New Custom Shaders Patch Versions & VR

### ISSUE THREAD

**Issue by MrLih** [ac-custom-shaders-patch/acc-extension-config#64]
Hello,

I just want to report to you a bug report related to Custom Shaders Patch in Content Manager, happening on VR users: it doesn't occur on 0.1.60 version, but on the latest ones it occurs, i didnt tried all of them but on 0.1.69, 0.1.71 definetly occurs and unfortunately there are some servers with requires you to have that paricular version in order to join, so it's very annoying to have those big margins and not be able to play on fullscreen. 

Picture: [https://ibb.co/ggCfTDp](url)

I hope that this can be fixed, thanks in advance !

**Comment by RustyChest** [comment]
This is not a bug, it's "Custom VR Mirroring onto the Main Screen" under Graphics Adjustment which you can disable.
